spring.application.name=LucidPlusTransfer

# === MySQL Database ===
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/lucidplus?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Muralikumar@790}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# === JPA/Hibernate ===
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update


# === JWT Configuration ===
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B59707896562966S6AS56A5S66S26S6D6V2V6FFGF66FF31F65B1FBF6F6BF9B9F3BFBF4B4FB9FF6BF3BFB216B
application.security.jwt.expiration=2592000000

email.sender.address=no-reply@lucidplustransfer.com
email.support.address=support@lucidplustransfer.com

app.otp.expiration.duration.minutes=5
app.otp.lockout.duration.minutes=120
app.otp.max.attempt.count=3

# === Mail ===
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=muralimadhaiyan1122@gmail.com
spring.mail.password=amkjzqkpnfbvtzrc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


app.cookie.max.age.minutes=3600